### ISSUE TITLE
Testing on Elgg 2 - Activating gives AJAX error as described below

### ISSUE THREAD

**Issue by michelesbw** [beck24/granular_access#5]
So, I'm learning Elgg and...
When activating current version 1.1.1 on Elgg 2.1.1 the info window of all plugins (lightbox) can't be opened anymore with error: "You can not access Ajax views directly. I didn't go on further check as this seems pretty bad."

https://github.com/beck24/granular_access/blob/master/views/default/js/granular_access.php#L6

I think it could dependo on the fact that the .live() function has been removed from jQuery's version user in Elgg 2

**Comment by beck24** [comment]
I can't replicate this specific issue, and .live() isn't part of this plugin at all

**Comment by juho-jaakkola** [comment]
I fixed this as I converted javascript to AMD: https://github.com/beck24/granular_access/commit/f1eacc3731dc7b5583a48306d5a0d44924b60ebc#diff-c4093be5dc7dba230b84dd20bec90ba0L6

**Comment by michelesbw** [comment]
Such a bad student, am not I? :D
