### ISSUE TITLE
Create lower branche(s), so master can be upgraded for Elgg 2

### ISSUE THREAD

**Issue by juho-jaakkola** [beck24/granular_access#6]
Minimum requirement is to branch current master into `1.8`.

AMD was introduced in Elgg 1.9, so master can then be upgraded to use it. A separate `1.9` branch can be added later, if there becomes a need to add some features that are supported only in Elgg 2.

**Comment by beck24** [comment]
Done, I added 1.8 for current, 1.12 (on the assumption that the same version should be compatible for 1.9 - 1.12) and master can be upgraded to 2.0

**Comment by juho-jaakkola** [comment]
To be exact, it should be `1.8`, `1.9` and `master`. After all semver was introduced in 1.9.

**Comment by beck24** [comment]
Yep, fixed
